services:
  backend:
    build: ./backend/DockerDemoBackendApi
    container_name: demo_backend
    environment:
      ASPNETCORE_URLS: http://+:5000
      ConnectionStrings__DefaultConnection: "Host=postgres;Database=docker_demo_db;Username=postgres;Password=postgres"
    depends_on:
      - postgres
  
  frontend:
    build: ./frontend
    container_name: demo_frontend
    depends_on:
      - backend
  
  postgres:
    image: postgres:18.3-bookworm
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docker_demo_db
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - "5432:5432"
  
  nginx:
    build: ./nginx
    container_name: demo_nginx
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend

volumes:
  pgdata: